---
title: "git_01"
author: "Ellyn Elizabeth Molzer"
date: "Septemer 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

A boat beneath a sunny sky,    
Lingering onward dreamily.   
In an evening of July —    
Children three that nestle near,    
Eager eye and willing ear,    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Love at the lips was touch  
As sweet as I could bear;  
And once that seemed too much;  
I lived on air  
That crossed me from sweet things,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

'Twas the night before Christmas,   
when all through the house   
Not a creature was stirring, not even a mouse;  
The stockings were hung by the chimney with care,  
In hopes that St. Nicholas soon would be there;  
The children were nestled all snug in their beds;  
While visions of sugar-plums danced in their heads;  
And mamma in her 'kerchief, and I in my cap,  
Had just settled our brains for a long winter's nap,  
When out on the lawn there arose such a clatter,  
I sprang from my bed to see what was the matter.  
Away to the window I flew like a flash,  
Tore open the shutters and threw up the sash.  
The moon on the breast of the new-fallen snow,  
Gave a lustre of midday to objects below,  
When what to my wondering eyes did appear,  
But a miniature sleigh and eight tiny rein-deer,  
With a little old driver so lively and quick,  
I knew in a moment he must be St. Nick.  
